service: algoreaforum
frameworkVersion: '3'

custom:
 dynamodb:
   stages:
     - local
   start:
     port: 7000
     inMemory: true
     heapInitial: 200m
     heapMax: 1g
     migrate: true
     convertEmptyValues: true

provider:
  name: aws
  environment:
    STAGE: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  deploymentMethod: direct
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:BatchWriteItem"
            - "dynamodb:DeleteItem"
          Resource:
            - Fn::GetAtt: [ForumTable, Arn]

functions:
  connection:
    handler: src/handlers/connection.handler
    events:
      - websocket:
          route: $connect
  disconnection:
    handler: src/handlers/disconnection.handler
    events:
      - websocket:
          route: $disconnect
  open-thread:
    handler: src/handlers/openThread.handler
    events:
      - websocket:
          route: open-thread
  close-thread:
    handler: src/handlers/closeThread.handler
    events:
      - websocket:
          route: close-thread
  subscribe:
    handler: src/handlers/subscribe.handler
    events:
      - websocket:
          route: subscribe
  unsubscribe:
    handler: src/handlers/unsubscribe.handler
    events:
      - websocket:
          route: unsubscribe
  thread-status:
    handler: src/threads/threadStatus.handler
    url:
      cors: true
  send-message:
    handler: src/handlers/sendMessage.handler
    events:
      - websocket:
          route: send-message
  heartbeat:
    handler: src/handlers/heartbeat.handler
    events:
      - websocket:
          route: heartbeat
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    ForumTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: forumTable
        TimeToLiveSpecification:
          AttributeName: "ttl"
          Enabled: true
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: "S"
          - AttributeName: time
            AttributeType: "N"
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE