service: forum
frameworkVersion: '3'

custom:
 dynamodb:
   stages:
     - dev
   start:
     port: 7000
     inMemory: true
     heapInitial: 200m
     heapMax: 1g
     migrate: true
     convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ForumTable, Arn]
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connection:
    handler: src/threads/connection.handler
    events:
      - websocket:
          route: $connect
  disconnection:
    handler: src/threads/disconnection.handler
    events:
      - websocket:
          route: $disconnect
  open-thread:
    handler: src/threads/openThread.handler
    events:
      - websocket:
          route: open-thread
  close-thread:
    handler: src/threads/closeThread.handler
    events:
      - websocket:
          route: close-thread
  follow:
    handler: src/threads/follow.handler
    events:
      - websocket:
          route: follow
  unfollow:
    handler: src/threads/unfollow.handler
    events:
      - websocket:
          route: unfollow
  has-thread:
    handler: src/threads/hasThread.handler
    events:
      - websocket:
          route: has-thread
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    ForumTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: forumTable
        TimeToLiveSpecification:
          AttributeName: "ttl"
          Enabled: true
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: "S"
          - AttributeName: time
            AttributeType: "N"
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE